const data = {
  products: [
    {
      name: "nike slim shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInstock: 10,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "nike slim pant",
      slug: "nike-slim-pant",
      category: "Pants",
      image: "/images/p2.jpg",
      price: 120,
      countInstock: 10,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality pant",
    },
    {
      name: "adidas slim pants",
      slug: "adidas-slim-pants",
      category: "Pants",
      image: "/images/p3.jpg",
      price: 120,
      countInstock: 10,
      brand: "adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality pants",
    },
    {
      name: "adidas slim shirt",
      slug: "adidas-slim-shirt",
      category: "Shirts",
      image: "/images/p4.jpg",
      price: 120,
      countInstock: 10,
      brand: "adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
  ],
};

export default data;
